print("bilal")  
print(2+2-3)
print("this is me bilal speaking from me itself")
print("all is ok except nothing is ok")
print("i want to eat something really facinates me")
print("you are so amazming that is start liking you")
print("there is something fishing going here i dont know why")
print("everyone likes me i dont know why")
print("are you okay baby are you alright")
print("there are culprits and black sheeps in our country")
print("is this something really fascinating or not")
print("there is good and evil both in you")
print("unleash the beast in you")
print("okay Allah accepts my all duas ecceth those are not good for me")
print(2+4+5**5)
print("everyone is so good is that i went sometimes paranoid")
print("there is good and there is bad as well so choice is upto yours if you want to what")
print("everythings is in ALLAH'S hand")
print("no body knows but Allah knows it all")
print("Allah's help is needed is everywhere")
print(''' iam completely agree with the fact that, everyone will leave this world oneday
and no body is free from the death.
life is so short enjoy the life and love every difficult''')

